/**
 * For more details on how to configure Wrangler, refer to:
 * https://developers.cloudflare.com/workers/wrangler/configuration/
 */
[build]
command = "pnpm install && pnpm run build"

[define]
# Optional: add any custom environment definitions if needed

name = "30tools"
main = ".open-next/worker.js"
compatibility_date = "2024-12-01"
compatibility_flags = [
	"nodejs_compat",
	"global_fetch_strictly_public"
]

[assets]
binding = "ASSETS"
directory = ".open-next/assets"

[observability]
enabled = true

# Optional: Smart Placement (if you want)
# [placement]
# mode = "smart"

# Optional: Environment Variables
# [vars]
# MY_VARIABLE = "production_value"

# Optional: Service Bindings
# [[services]]
# binding = "MY_SERVICE"
# service = "my-service"
